version: "3.9"

services:
  nginx:
    container_name: ca-nginx-questionnaire
    image: nginx:1.23.1
    working_dir: /var/www
    volumes:
      # change mapping to serve from `public` dir
      - ../${LOCAL_DIR}:/var/www
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - php

  php:
    container_name: ca-php-questionnaire
    # xdebug
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # image: php:8.1.1-fpm-alpine3.15
    build: ./php/
    working_dir: /var/www
    volumes:
      - ../${LOCAL_DIR}:/var/www

  node:
    container_name: ca-node-questionnaire
    image: node:16.17-alpine3.15
    working_dir: /var/www
    # this prevents container from stopping immediately after start
    tty: true
    volumes:
      - ../${LOCAL_DIR}:/var/www

  mysql:
    image: mysql
    container_name: ca-mysql-questionnaire
    env_file:
      - ./mysql/.env
    volumes:
      - ./mysql/data/mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
